package cn.aposoft.administrativedivision.db.mappers;

import cn.aposoft.administrativedivision.db.AdministrativeDivision;
import cn.aposoft.administrativedivision.db.AdministrativeDivisionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdministrativeDivisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    long countByExample(AdministrativeDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    int deleteByExample(AdministrativeDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    int insert(AdministrativeDivision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    int insertSelective(AdministrativeDivision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    List<AdministrativeDivision> selectByExample(AdministrativeDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    AdministrativeDivision selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") AdministrativeDivision record, @Param("example") AdministrativeDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    int updateByExample(@Param("record") AdministrativeDivision record, @Param("example") AdministrativeDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    int updateByPrimaryKeySelective(AdministrativeDivision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrative_division
     *
     * @mbg.generated Mon Jun 05 17:51:45 CST 2017
     */
    int updateByPrimaryKey(AdministrativeDivision record);
}