package cn.aposoft.administrativedivision.db.mappers;

import cn.aposoft.administrativedivision.db.DivisionYearlyDetail;
import cn.aposoft.administrativedivision.db.DivisionYearlyDetailExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface DivisionYearlyDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	long countByExample(DivisionYearlyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	int deleteByExample(DivisionYearlyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	int insert(DivisionYearlyDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	int insertSelective(DivisionYearlyDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	List<DivisionYearlyDetail> selectByExample(DivisionYearlyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	DivisionYearlyDetail selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	int updateByExampleSelective(@Param("record") DivisionYearlyDetail record,
			@Param("example") DivisionYearlyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	int updateByExample(@Param("record") DivisionYearlyDetail record,
			@Param("example") DivisionYearlyDetailExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	int updateByPrimaryKeySelective(DivisionYearlyDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table division_yearly_detail
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	int updateByPrimaryKey(DivisionYearlyDetail record);
}