package cn.aposoft.administrativedivision.db;

public class DivisionYearlyDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column division_yearly_detail.id
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column division_yearly_detail.statistical_id
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	private Integer statisticalId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column division_yearly_detail.code
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column division_yearly_detail.name
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column division_yearly_detail.id
	 * @return  the value of division_yearly_detail.id
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column division_yearly_detail.id
	 * @param id  the value for division_yearly_detail.id
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column division_yearly_detail.statistical_id
	 * @return  the value of division_yearly_detail.statistical_id
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	public Integer getStatisticalId() {
		return statisticalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column division_yearly_detail.statistical_id
	 * @param statisticalId  the value for division_yearly_detail.statistical_id
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	public void setStatisticalId(Integer statisticalId) {
		this.statisticalId = statisticalId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column division_yearly_detail.code
	 * @return  the value of division_yearly_detail.code
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column division_yearly_detail.code
	 * @param code  the value for division_yearly_detail.code
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column division_yearly_detail.name
	 * @return  the value of division_yearly_detail.name
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column division_yearly_detail.name
	 * @param name  the value for division_yearly_detail.name
	 * @mbg.generated  Mon Jun 05 17:51:45 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}
}